---
title: "Helpful public databases"
format: html
editor: visual
---

***Australian and international publicly available databases ready for data analysis***

My aim here is to compile a list of publicly available databases (with an Australian focus as I'm based in Australia) which relate to common social and welfare groups or organistions. These databases are ready for analysis and I use them myself for analysis with the aim that findings from these data can help someone out there make evidence based decisions or an informed choice for a better outcome.

---
## Australia
---

### Australian Road Deaths Database

**Publisher**: [Bureau of Infrastructure and Transport Research Economics (BITRE)](https://www.bitre.gov.au)

**Description**: The ARDD provides basic details of road traffic crash fatalities in Australia as reported by the police each month to the State and Territory road safety authorities.

**Link**: <https://www.bitre.gov.au/statistics/safety/fatal_road_crash_database>

------------------------------------------------------------------------

### Research Data Australia- Social Work, Community Services & Policy

**Publisher**: [Australian Research Data Commons (ARDC)](https://researchdata.edu.au/)

**Description**: Find, access, and re-use data for research from over one hundred Australian research organisations, government agencies, and cultural institutions. These are filtered results relating to Social Work and Community Services databases.

**Topics**: #Adoption #Foster Care #Children #Disadvantaged #Wellbeing #CaLD #Trauma #Counselling #Neurodiversity #Families #Young People #Prisoners #Social Workers #Women

**Link**: <https://researchdata.edu.au/search/#!/rows=15/sort=list_title%20asc/class=collection/collection_type=-type%3Asoftware/p=1/anzsrc-for=1607/anzsrc-for=1605/q=/advanced=true/>

------------------------------------------------------------------------

### Data4Good- Publicly Available Datasets based on the UN Sustainable Development Goals

**Publisher**: [Data4Good)](https://data4good.com.au/data/)

**Description**: A collection of reputable public datasets available from around the web grouped and filtered according to the UN Sustainable Development Goals.

**Topics**: #No Poverty #Zero Hunger #Good Health and Well-being #Quality Education #Gender Equality #Clean Water and Sanitation #Affordable and Clean Energy #Decent Work and Economic Growth #Industry, Innovation and Infrastructure #Reduced Inequality #Sustainable Cities and Communities #Responsible Consumption and Production #Climate Action #Life Below Water #Life on Land #Peace and Justice Strong Instituitions #Partnerships to achieve the Goal #Government Census Data.

**Link**: <https://data4good.com.au/data/>

------------------------------------------------------------------------

### Australia Health and Aged Care database

**Publisher**: [Australian Government- Department of Health and Aged Care)](https://www.health.gov.au/)

**Description**: Health and Aged Care data collected and administered by Commonwealth Department of Health.

**Topics**: #Aboriginal and Torres Strait Islander health #Aged care #Bladder and bowel #Cancer #Chronic conditions #Communicable diseases #Covid-19 #Dental health #General practice #Health data and medical research #Health technologies and digital health #Health workforce #Hospital care #Immunisation #Medical devices #Medicare #Medicines #Preventive health #Primary care #Private health insurance #Rural health

**Link**: <https://www.health.gov.au/resources/publications?f%5B0%5D=h_publication_type%3ADataset>

------------------------------------------------------------------------

### States and Territories publicly available databases

Each state and territory in Australia has their own publicly accessible database. They're listed below. Most can be filtered based on your topic of interest.

<ul>

<li>**Australian Capital Territory (ACT)**: [dataACT](https://www.data.act.gov.au/browse)</li>

<li>**New South Wales (NSW)**: [Data.NSW](https://data.nsw.gov.au/data/dataset)</li>

<li>**Northern Territory (NT)**: [NTG Open Data Portal](https://data.nt.gov.au/)</li>

<li>**Queensland (QLD)**: [Open Data Portal](https://www.data.qld.gov.au/dataset)</li>

<li>**South Australia (SA)**: [Data.SA](https://data.sa.gov.au/data/dataset)</li>

<li>**Tasmania (TAS)**: Not Available</li>

<li>**Victoria (VIC)**: [dataVic](https://discover.data.vic.gov.au/dataset/)</li>

<li>**Western Australia (WA)**: [dataWA](https://catalogue.data.wa.gov.au/dataset)</li>

</ul>

------------------------------------------------------------------------

### Australian Bureau of Statistics

**Publisher**: [Australian Government- Australian Bureau of Statistics)](https://www.abs.gov.au/)

**Description**: Of course we can't in Australia talk about data without mentioning Australia's go to Organisation for reliable and quality data. You can get any dataset relating to Australia from here as a result of the hardwork by the Data Scientists at the ABS.

**Link**: <https://www.abs.gov.au/>

---
## Worldwide
---

### UNICEF Database on Children and Women welfare around the world

**Publisher**: [UNICEF](https://www.unicef.org/)

**Description**: UNICEF, the United Nations agency for children, works to protect the rights of every child, especially the most disadvantaged and those hardest to reach. The Data Team is the global go-to for data on children. It leads the collection, validation, analysis, use and communication of the most statistically sound, internationally comparable data on the situation of children and women around the world. These data, upheld for quality and integrity, are accessible as a global public good.

**Topics**: #Adolescents Child & Adolescent Health #Children with disabilities #Climate change #Early childhood development #Education #Gender equality #HIV/Aids #Maternal and newborn health #Migration #Mortality #Child nutrition #Poverty #Protection #Water, sanitation and hygiene

**Link**: <https://data.unicef.org/resources/resource-type/datasets/>
