name: Update badges

on: push

jobs:
  update-professional:
    name: Update professional with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - professional
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: <eugene-wong.71f6a6cd_credly>
